### ISSUE TITLE
how to write the schedule for 'last day of each month'?

### ISSUE THREAD

**Issue by geneshen** [citusdata/pg_cron#102]
Hi,
     I want to know how to write the cron schedule for 'last day of each month',I have tried '0 22 L * *',it shows invalid schedule

**Comment by geneshen** [comment]
sorry，I Have find a solution

**Comment by hanefi** [comment]
I suggest you have 3 seperate rules as suggested in [this StackOverflow answer](https://stackoverflow.com/a/6139310/11190430)

```
55 23 30 4,6,9,11        * myjob.sh
55 23 31 1,3,5,7,8,10,12 * myjob.sh
55 23 28 2               * myjob.sh
```
