### ISSUE TITLE
v13 support

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/pg_cron#109]
Hi,

When will you release new pg_cron that works against v13? We are working on RPM (and Debian/Ubuntu) packaging.

Regards, Devrim

**Comment by marcocitus** [comment]
Soon (1-2 weeks), it'll get bundled with some bigger changes.

**Comment by rachekalmir** [comment]
Any update on this release?

**Comment by df7cb** [comment]
Ping from Debian as well.

**Comment by marcocitus** [comment]
v1.3.0 is now available

**Comment by df7cb** [comment]
Thanks!

**Comment by devrimgunduz** [comment]
Thanks!
