### ISSUE TITLE
Add  'database' parameter to cron.schedule

### ISSUE THREAD

**Issue by alexeyklyukin** [citusdata/pg_cron#13]
I think it could be useful for providing containers with pg_cron installed to set the cron.database_name to a certain fixed database (even 'postgres') and allow scheduling actual tasks against any other database on the same cluster. Everything is already there, except for the cron.schedule function support. Does it make sense to make another version of this function with an additional  'database'  parameter?

**Comment by marcocitus** [comment]
Sure, would you mind taking a look at #14?

**Comment by marcocitus** [comment]
On second thought, the administrator may have put certain restrictions on `pg_hba.conf` which would have normally prevented a the user from connecting to another database from a remote location. The working assumption is that pg_cron should not be able to do anything that a user could not do by connecting to the database himself.

Superuser could achieve this by performing updates on `cron.job`:
```
CREATE OR REPLACE FUNCTION cron.schedule(schedule text, command text, database_name text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
        job_id bigint;
BEGIN
        SELECT cron.schedule(schedule, command) INTO job_id;
        UPDATE cron.job SET database = database_name WHERE jobid = job_id;
END;
$function$
```

**Comment by jan-zajic** [comment]
? so what about to include function schedule from your comment into pg_cron extension script pg_cron.sql?

**Comment by BuSHari** [comment]
> On second thought, the administrator may have put certain restrictions on `pg_hba.conf` which would have normally prevented a the user from connecting to another database from a remote location. The working assumption is that pg_cron should not be able to do anything that a user could not do by connecting to the database himself.
> 
> Superuser can specify a database by performing an update on `cron.job`:
> 
> ```
> CREATE OR REPLACE FUNCTION cron.schedule(schedule text, command text, database_name text)
>  RETURNS void
>  LANGUAGE plpgsql
> AS $function$
> DECLARE
>         job_id bigint;
> BEGIN
>         SELECT cron.schedule(schedule, command) INTO job_id;
>         UPDATE cron.job SET database = database_name WHERE jobid = job_id;
> END;
> $function$
> ```

Hi,

I tried that solution, but im getting `connection failed` (I'm the admin and used superuser).
How can i scheduled task to other databases?

**Comment by marcocitus** [comment]
We now have a cron.alter_job function, which can be used to change the database, and is only callable by superuser.

**Comment by marcocitus** [comment]
This is implemented by cron.schedule_in_database.
