### ISSUE TITLE
pg_dump in pg_cron

### ISSUE THREAD

**Issue by marshmello275** [citusdata/pg_cron#136]
Can someone help on 
how to create a pg_dump job using pg_cron?
need to run **pg_dump postgres > temp.sql -U postgres** in pg_cron
or any other alternative to achieve this in pg_cron

**Comment by marshmello275** [comment]
//dump postgres db on every Saturday at 3:30am (GMT)
SELECT cron.schedule('30 3 * * 6', $$pg_dump postgres > temp.sql -U postgres$$);

is above command correct for it?

**Comment by ploef** [comment]
Hi,

This is what I'm looking for also.

Kind regards,
Peter
