### ISSUE TITLE
Pg_cron installation fail for postgresql11

### ISSUE THREAD

**Issue by manojmca2011** [citusdata/pg_cron#145]
Hey,

I have downloaded the pg_cron source code from "git clone https://github.com/citusdata/pg_cron.git"
but when i am trying to install that showing error:- 
---------
 pg_cron]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -pg -DLINUX_PROFILE -O2 -fPIC -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/app/postgres/1101/include -I. -I./ -I/app/postgres/1101/include/server -I/app/postgres/1101/include/internal  -D_GNU_SOURCE   -c -o src/job_metadata.o src/job_metadata.c -MMD -MP -MF .deps/job_metadata.Po
src/job_metadata.c: In function ‘GetRoleOidIfCanLogin’:
src/job_metadata.c:381:14: error: ‘FormData_pg_authid’ has no member named ‘oid’
  return rform->oid;
              ^
src/job_metadata.c:382:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/job_metadata.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make: *** [src/job_metadata.o] Error 1
-------
Could you please help me to resolve this issue.

**Comment by marcocitus** [comment]
Thanks, fixed now.
