### ISSUE TITLE
Log-Messages and Cron-Job status as running forever

### ISSUE THREAD

**Issue by bangyogesh** [citusdata/pg_cron#160]
Hello there,

We have been using pg_cron to schedule and run a stored procedure at pre-defined intervals. The stored-procedure has a complex business logic and needs to log the steps along with dynamic-SQL and the data as it iterates through the records. Once the job is fired, we observed that after certain iterations (loop) in the same stored procedure, the logging stops and the Job status in **job_run_details** table shows as **'running'** forever.  (Note- we have been using the AWS RDS managed instance).

The sample code is on the similar lines of the example shared below.  Please suggest if we are missing something.

Example -
` CREATE OR REPLACE PROCEDURE public.logtest()
 LANGUAGE plpgsql
AS $procedure$
	
	declare 	
		iCounter integer;
	BEGIN
		for iCounter in 1..200 loop
			raise notice 'ATTEMPT-%,123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899200123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899300123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899400123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899500',iCounter;		
		end loop;
	exception
		WHEN OTHERS THEN
			RAISE NOTICE 'Exception occurred in logtest. Parameters  SQLSTATE=% ,SQLERRM=% ',SQLSTATE, SQLERRM  ;	
	
	END;
$procedure$
; 
`

**Comment by marcocitus** [comment]
I suspect this was due to the bug fixed in https://github.com/citusdata/pg_cron/pull/152
