### ISSUE TITLE
Issue: could not access file "pg_cron": No such file or directory

### ISSUE THREAD

**Issue by GloriaGreatGreat** [citusdata/pg_cron#163]
Hi,

I've used pg_cron for a while building docker images with postgres, but started to face this 

could not access file "pg_cron": No such file or directory

issue since last month.

I've been using the same  pg_cron version 1.3.1 and same docker file, after built the image and let it run, the container would fail with the error message. Was there anything changed to pg_cron version 1.3.1?

**Comment by marcocitus** [comment]
It seems the package is not installed. There was no significant change.
