### ISSUE TITLE
Crash with job_name argument on schedule function

### ISSUE THREAD

**Issue by sguinebert** [citusdata/pg_cron#164]
I encounter some crash with recent updates (Postgresql 13 citus 10). This function return fatal error 7 and crash the connection (minimal reproducible exemple):

SELECT cron.schedule('4dbb95f6-bb8c-4a29-99ab-8ae5dcf56ca9', '45 09 17 11 *','');

Depending on the string argument, the input works but with jobname truncated or crash.

Alter function argument IN job_name from Name to text type seem to resolve the problem

**Comment by marcocitus** [comment]
Did you run ALTER EXTENSION pg_cron UPDATE? The argument type of the function changed in 1.4

**Comment by sguinebert** [comment]
No I did not update, but please consider to close the issue since I can't reproduce anymore the bug
Thank you
