### ISSUE TITLE
Persistent error in docker build: "pg_cron can only be loaded via shared_preload_libraries"

### ISSUE THREAD

**Issue by snspinn** [citusdata/pg_cron#167]
### The issue
I've tried quite a few different iterations of my docker build and I consistently come against this error when I run `CREATE EXTENSION pg_cron;`

```
mydb=# CREATE EXTENSION pg_cron;
ERROR:  pg_cron can only be loaded via shared_preload_libraries
HINT:  Add pg_cron to the shared_preload_libraries configuration variable in postgresql.conf.
```

My config is persisted in a mounted volume and indeed has the two recommended lines in it:
```
shared_preload_libraries = 'pg_cron'
cron.database_name = 'mydb'
```

If I try running the same command in the postgres db, I get a different error:
```
postgres=# CREATE EXTENSION pg_cron;
ERROR:  can only create extension in database mydb
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'postgres' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
```

I get the same error in `mydb` whether I have restarted (`pg_ctl -D "$PGDATA" -m fast -w stop`) the postgres db or not. It all feels a bit circular. Any ideas?

### Musings
My planned debug steps (until I find one that works)

- Build with an Ubuntu base image (I notice that this is the one timescale's docker-ha image uses)
- Build without timescaldb
- Any ideas put forward

### Build (Dockerfile)
```
FROM postgres:13-buster

RUN apt-get update && apt-get install -y wget curl

RUN curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.deb.sh |  bash
RUN apt-get update || exit 1;
RUN apt-get install -y timescaledb-2-postgresql-13 -y postgresql-13-postgis-3 postgresql-13-cron || exit 1;
RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null;

COPY entrypoint/ /docker-entrypoint-initdb.d/
```

### Edit/addendum

Before this I was struggling with similar issue as these ([first](https://github.com/citusdata/pg_cron/issues/55), [second](https://github.com/citusdata/pg_cron/issues/129)) issues, so admittedly, a bit of a noob with pg_cron.

**Comment by snspinn** [comment]
I don't know if I'll get around to solving this one but I thought I'd add some notes here, in case it points someone in the right direction in future.

After some sleep and creating my "dream" database by ditching docker and installing directly on a base OS (Ubuntu 20.04), I noticed a difference between `postgres:13-buster` and my manual install. Namely, the docker image keeps everything in `/var/lib/postgresql/data` whereas on a "normal" installation, things like `pg_hba.conf` and `postgresql.conf` are kept in `/etc/postgresql/[pg_version]` (your install may differ).


## To illustrate this point...
### Non-dockerised/"normal" install (psql)
```
postgres=# SHOW hba_file;
              hba_file
-------------------------------------
 /etc/postgresql/13/main/pg_hba.conf
(1 row)

postgres=# SHOW config_file;
               config_file
-----------------------------------------
 /etc/postgresql/13/main/postgresql.conf
(1 row)

postgres=# SHOW data_directory;
       data_directory
-----------------------------
 /var/lib/postgresql/13/main
(1 row)

```

### Docker container (psql)
```
postgres=# SHOW hba_file;
               hba_file
--------------------------------------
 /var/lib/postgresql/data/pg_hba.conf
(1 row)

postgres=# SHOW config_file;
               config_file
------------------------------------------
 /var/lib/postgresql/data/postgresql.conf
(1 row)

postgres=# SHOW data_directory;
      data_directory
--------------------------
 /var/lib/postgresql/data
(1 row)
```

If this is the root issue, I have yet to find a workaround to get this working properly.

**Comment by sgrinko** [comment]
Look at my docker container. Maybe she will like it :)
https://github.com/sgrinko/docker-postgres
Many extensions have been introduced. Including the extension pg_cron

**Comment by snspinn** [comment]
Thanks @sgrinko . 
I think I will borrow the relevant lines from your Dockerfile. You've saved me hours of testing and uncertainty!

**Comment by valoricDe** [comment]
Out of curiousity, what are the relevant lines? ^^,
