### ISSUE TITLE
Getting job_run_details while the command is still running

### ISSUE THREAD

**Issue by TomasHubelbauer** [citusdata/pg_cron#174]
Hi, I am wondering the pg_cron works by running the supplied command and only then creating a new row in `cron.job_run_details` or whether that row gets created with `NULL`s for `status`, `return_message` and `end_time` first?

I tried to test this to find out by using a `pg_sleep(30)` and querying `cron.job_run_details`, which was timing out, but then I learnt that `pg_sleep` locks up the entire server process so its no wonder I was not able to query it.

I also tried by using `pgsql-http` and calling `select content, status from http_get('https://deelay.me/30000/https://example.com')`. My idea is that AFAIK this uses Postgres background workers, so it should not lock up the database even if the requests take long enough time for me to be able to check if the `cron.job_run_details` row has been created for the ongoing cron schedule run.

However that extension enforces a 5 second timeout and I am not sure yet how to configure that timeout to be longer on Supabase. I will keep trying, but in the meanwhile I figured I'd ask this question.

My motivation for finding this out is that I would like to build a UI that displays the rows of `cron.job_run_details` and I would like for ongoing requests to also appear in it. Alternatively, is there a different table in the `cron` schema that keeps track of the ongoing runs? Or some other mechanism to get this information?

Thank you

**Comment by marcocitus** [comment]
cron.job_run_details shows ongoing runs with status 'running'
