### ISSUE TITLE
Bug installingt with apt 

### ISSUE THREAD

**Issue by ppKrauss** [citusdata/pg_cron#175]
Using UBUNTU 12 and pg12.

-----

```sh
psql postgres://postgres@localhost -c "select version()"
 #   PostgreSQL 12.9 (Ubuntu 12.9-2.pgdg20.04+1) ...
# ... afer sudo apt update; sudo apt upgrade
sudo apt install postgresql-12-cron
  # ... all ok.
sudo service postgresql restart
psql postgres://postgres@localhost -c "CREATE EXTENSION pg_cron"
 # ERROR:  unrecognized configuration parameter "cron.database_name"
 # CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
 
psql postgres://postgres@localhost -c "show hba_file"
  # /etc/postgresql/12/main/pg_hba.conf
grep trust /etc/postgresql/12/main/pg_hba.conf
  # host    all             all             127.0.0.1/32            trust

psql postgres://postgres@localhost -c "show config_file"
  # /etc/postgresql/12/main/postgresql.conf
grep cron  /etc/postgresql/12/main/postgresql.conf
 # empty!
```
Conclusion: the "unrecognized configuration" **is an installation bug**... How to fix it?

**Comment by ppKrauss** [comment]
Hum... Seems a problem on README, it say 

* *"By default, the pg_cron background worker expects its metadata tables to be created in the "postgres" database.*"<br/> interpretation: there is a "default behaviour", we install with  `apt` and **do nothing** more.
* *"However, you can configure ..."*, so it is not "you MUST configuro".

README bug: **please change "you can" to "you MUST"**.

**Comment by marcocitus** [comment]
> Conclusion: the "unrecognized configuration" is an installation bug... How to fix it?

You need to add `shared_preload_libraries = 'pg_cron'` to postgresql.conf

> README bug: please change "you can" to "you MUST".

This was correct in the sense that you can configure the database name.

Additionally, you MUST configure shared_preload_libraries (preceding sentences). Clarified this a bit by separating them into 2 blocks.
