### ISSUE TITLE
Is it possible to configure pg_cron to execute linux os command?

### ISSUE THREAD

**Issue by yinan8128** [citusdata/pg_cron#177]
Hello,

We need to use cronjob to run linus os command to trigger pg_repack for some bigger table indexes only at the leader ndoe, if use linux os cronjob then need to check which node is leader node and maintain it in os level and so on.

As compared pg_cron with linux os cronjob, pg_cron has so many advantages , so is it possible to configure pg_cron to execute linux os command? Thanks

**Comment by yinan8128** [comment]
Hi,

Any update please? Thanks

**Comment by marcocitus** [comment]
We don't plan to implement that, but you should be able to do it via PL/Python.
