### ISSUE TITLE
pg_cron did not do anything

### ISSUE THREAD

**Issue by mzwettler2** [citusdata/pg_cron#186]
SYSTEM:
=======
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Linux tstm49265 3.10.0-1160.45.1.el7.x86_64 #1 SMP Fri Sep 24 10:17:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
postgresql12-12.9-1PGDG.rhel7.x86_64
pg_cron_12-1.4.1-1.rhel7.x86_64

INSTALLATION:
=============
1. CREATE EXTENSION pg_cron;
2. GRANT USAGE ON SCHEMA cron TO public; 
3. added db user stcadm to .pgpass
4. added db user stcadm to pg_hba.conf (trust)
5. modified postgresql.conf:
> cron.database_name = 'pdb_l60_oiz'
> shared_preload_libraries = 'auto_explain, pg_stat_statements, pg_cron, pg_statsinfo, pg_store_plans'

USAGE:
======
stcadm@pcl_l666:pdb_l60_oiz > select cron.schedule('40 10 * * *','insert into stcadm.test values (9999)');
schedule
----------
        8
(1 row)

stcadm@pcl_l666:pdb_l60_oiz >  select * from cron.job;
jobid |  schedule   |                command                | nodename  | nodeport |  database   | username | active
-------+-------------+---------------------------------------+-----------+----------+-------------+----------+--------
    8 | 40 10 * * * | insert into stcadm.test values (9999) | localhost |     5432 | pdb_l60_oiz | stcadm   | t
(1 row)

PROBLEM:
========
nothing happend...
... and there is only 1 pg_cron related entry in the logfile:
> 2022-05-12 10:03:08 CEST 92913 LOG:  pg_cron scheduler started

I already tried the "nodename" workarounds from here:
https://github.com/citusdata/pg_cron/issues/48
did not change anything.

QUESTION:
=========
any idea?

**Comment by marcocitus** [comment]
Anything in the log?

It might be because pg_cron works in GMT and your server is in CEST. Maybe schedule a job every minute to verify whether scheduling works.

**Comment by mzwettler2** [comment]
Yes it has been the timezone issue GMT / CEST.

Thanks,  Markus
