### ISSUE TITLE
1.4.1 build error on Fedora 36

### ISSUE THREAD

**Issue by devrimgunduz-dh** [citusdata/pg_cron#187]
Hi,

pg_cron does not build on Fedora 36, GCC 12.1:

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Iinclude -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o src/entry.bc src/entry.c
> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Iinclude -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o src/job_metadata.bc src/job_metadata.c
> error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]
> make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1070: src/entry.bc] Error 1
> make[1]: *** Waiting for unfinished jobs....
> error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]
> make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1070: src/job_metadata.bc] Error 1
> make[1]: Leaving directory '/var/lib/pgsql/rpm14/BUILD/pg_cron-1.4.1'
> error: Bad exit status from /var/tmp/rpm-tmp.VOWhr9 (%build)
> 

Can you please take a look?

Regards, Devrim

**Comment by devrimgunduz-dh** [comment]
ping.

**Comment by devrimgunduz** [comment]
ping.

**Comment by marcocitus** [comment]
I updated the flag in https://github.com/citusdata/pg_cron/commit/82573a41eb82774e365ee6d149070f6576530d95 , does that work?

**Comment by devrimgunduz** [comment]
@marcocitus thanks a lot, patch fixes it. Are you planning any release soon, or should I just add this as  a temp patch to the RPMs?

Regards, Devrim

**Comment by marcocitus** [comment]
>  or should I just add this as a temp patch to the RPMs?

I think using this commit for the RPM would br good. It's v1.4.2+Makefile change.

**Comment by devrimgunduz-edb** [comment]
Thanks a lot! We can close this
