### ISSUE TITLE
How to (re)load pg_cron scheduler

### ISSUE THREAD

**Issue by alexitheodore** [citusdata/pg_cron#188]
I have a frequent scenario where I need to kick all connections off a database to do updates. This includes the pg_cron scheduler. What I've found is that after I do that, the only way I know to get it back again (i.e. to restore pg_cron functionality) is to restart postgres... which I really don't want to do. Is there another/better way to get it running again?

**Comment by owen-xie** [comment]
Looking forward to someone's answer

**Comment by 1schmnkS** [comment]
same here ... I also always need to restart postgres -> would be highly interested in a more elegant way to start cron scheduler

**Comment by sgronblo** [comment]
Almost one year later. Is there no known way to do this?
