### ISSUE TITLE
Regression test failing for v1.4.2

### ISSUE THREAD

**Issue by crunchymaggie** [citusdata/pg_cron#195]
PG versions affected: 10-12
Tested on Rocky 8

Steps to Reproduce:

1. Download the pgdg repo file and key from PGDG:
`sudo dnf install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm`
2. `sudo dnf module disable postgresql`
3. `sudo dnf install postgresql10*`
4. Clone repository `git clone https://github.com/citusdata/pg_cron.git`
5. Install dependencies `sudo dnf install openssl-devel libxml2-devel openldap-devel make gcc redhat-rpm-config `
6. `cd pg_cron`
7. `git checkout v1.4.2`
8. `PATH=/usr/pgsql-10/bin:$PATH make`
9. `sudo PATH=/usr/pgsql-10/bin:$PATH make install`
10. Initialize postgres`sudo su postgres -c "cd ~/ ; /usr/pgsql-10/bin/initdb --data-checksums -D /var/lib/pgsql/10/data -E utf8 --locale=en_US.UTF-8"`
11. Add pg-cron `sudo -H -u postgres bash -c "echo \"shared_preload_libraries='pg_cron'\" >> /var/lib/pgsql/10/data/postgresql.conf"`
12. Start postgres `sudo su postgres -c "cd ~/ ; /usr/pgsql-10/bin/pg_ctl -w -D /var/lib/pgsql/10/data -l /var/lib/pgsql/logfile start"`
13. Create a role for the user, replace "BOBBY" with your user. `sudo su postgres -c "psql -c 'CREATE ROLE BOBBY WITH LOGIN SUPERUSER;'"`
14. `make installcheck PG_CONFIG=/usr/pgsql-10/bin/pg_config`

The output of the `make installcheck` is the following:
```============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============
running on port 50869 with PID 45634
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test pg_cron-test             ... FAILED
============== shutting down postmaster               ==============

======================
 1 of 1 tests failed.
======================
```

The output of the regression.diff file is the following:
```*** /opt/git/pg_cron/expected/pg_cron-test.out	2022-07-20 15:34:10.793676051 -0400
--- /opt/git/pg_cron/results/pg_cron-test.out	2022-07-22 11:42:37.480555058 -0400
***************
*** 197,205 ****
--- 197,212 ----
  CREATE TYPE current_setting AS ENUM ('cron.database_name');
  CREATE OR REPLACE FUNCTION public.func1(text, current_setting) RETURNS text
      LANGUAGE sql volatile AS 'INSERT INTO test(data) VALUES (current_user); SELECT current_database();';
+ ERROR:  return type mismatch in function declared to return text
+ DETAIL:  Actual return type is name.
+ CONTEXT:  SQL function "func1"
  CREATE OR REPLACE FUNCTION public.func1(current_setting) RETURNS text
      LANGUAGE sql volatile AS 'INSERT INTO test(data) VALUES (current_user); SELECT current_database();';
+ ERROR:  return type mismatch in function declared to return text
+ DETAIL:  Actual return type is name.
+ CONTEXT:  SQL function "func1"
  CREATE CAST (current_setting AS text) WITH FUNCTION public.func1(current_setting) AS IMPLICIT;
+ ERROR:  function public.func1(current_setting) does not exist
  CREATE EXTENSION pg_cron VERSION '1.4';
  select * from public.test;
   data

======================================================================
```

I suspect that this commit `53a2e006fb5605daba953f029f31e673b28ccf7e` is when the test broke.

**Comment by marcocitus** [comment]
Fixed in 1.4.2

**Comment by df7cb** [comment]
It fails like that with PG 10..12. PG 13+ is ok.

**Comment by crunchymaggie** [comment]
I confirmed it's not an issue for PG13+ and changed the issue to say PG10-12. 

Does this mean that this regression failure can be disregarded for PG10-12 or is it a bug?

**Comment by df7cb** [comment]
This is a bug with PG10..12 that prevents me from updating the pg-cron Debian package to 1.4.2.

**Comment by df7cb** [comment]
Build log with failures:
https://pgdgbuild.dus.dg-i.net/job/pg-cron-binaries/36/architecture=amd64,distribution=kinetic/console#console-section-11
