### ISSUE TITLE
[Feature request] Do not limit max_running_jobs by hardcoded values

### ISSUE THREAD

**Issue by Hdrtblsh** [citusdata/pg_cron#197]
It would be great to move the limits of cron.max_running_jobs (currently hardcoded limit is 32 for !UseBackgroundWorkers and 5 for UseBackgroundWorkers) to a user defined variables (with default being 32 and 5 respectively)
https://github.com/citusdata/pg_cron/blob/main/src/pg_cron.c#L271

**Comment by marcocitus** [comment]
It is the default rather than the limit that is semi-hard-coded. The limit is MaxConnections / max_worker_processes - 1, which is the maximum the database can support.
