### ISSUE TITLE
Does not run the task when specifying a schedule.

### ISSUE THREAD

**Issue by ezecrt** [citusdata/pg_cron#20]
Install and compile the module without problems, but when creating a task, I only run those I program every 1 minute (* * * * *), but if the same task I put a specific time to run a task every day For example: (30 17 * * *) does not run, does not even leave a trace in the log, is this normal? Thank you.

**Comment by marcocitus** [comment]
Note the pg_cron schedule is in GMT. You might want to correct for timezone differences.
