### ISSUE TITLE
Version of package 1.4.2 does not match with version installed extension 1.4-1

### ISSUE THREAD

**Issue by ofigenov** [citusdata/pg_cron#202]
I have automation, which is based on the equality of the minor version of the rpm-package and extension. This worked fine not only for  pg_cron but also for other extensions: pgAudit, timescaledb, pg_pathman and others. Until it turned out that a new package appeared in which version 1.4.2, and after installing the extension in the postgres itself, the extension shows version 1.4-1. You can explain - this is a error and who is to blame for it? Or you have somehow changed the name of versions and now they may not equal.

CentOS Linux release 7.9.2009 (Core):

```
# yum list pg_cron*14*
Installed Packages
pg_cron_14.x86_64                                                1.4.2-1.rhel7                                                @pgdg14

# rpm -ql pg_cron_14.x86_64
...
/usr/pgsql-14/share/extension/pg_cron.control
....
less /usr/pgsql-14/share/extension/pg_cron.control
...
default_version = '1.4-1'
...


```
in psql:

```
\dx
...
pg_cron            | 1.4-1   | public     | Job scheduler for PostgreSQL
...
```

**Comment by marcocitus** [comment]
SQL schema and binary version are somewhat independent of each other. The 1.4.2 release did not change the SQL schema, so the version ("1.4-1") is unchanged.
