### ISSUE TITLE
cron.schedule is inserting corrupt job name

### ISSUE THREAD

**Issue by klmallory** [citusdata/pg_cron#209]
```
SELECT cron.schedule('EXPORT ec3cedbf-2068-4292-9e72-4a3109371714 uat','00 00 04 10 *',
$CRON$
select 1;
$CRON$)
```

Inserts a job with a job name of 

XPORT ec3cedbf-2068-4292-9e72-4a3

The whole job row looks like this:

"jobid"	"schedule"	"command"	"nodename"	"nodeport"	"database"	"username"	"active"	"jobname"

561	"00 00 04 10 *"	"select 1;"	"localhost"	5432	"uat2_main"	"acme"	true	**"XPORT ec3cedbf-2068-4292-9e72-4a3"**

We have pg cron version 1.3:
"oid"	"extname"	"extowner"	"extnamespace"	"extrelocatable"	"extversion"	"extconfig"	"extcondition"
"372301083"	"pg_cron"	"10"	"2200"	false	**"1.3"**	"{372301087,372301085,372301109,372301107}"	"{"""","""","""",""""}"

**Comment by piotrwielgolaski-tomtom** [comment]
In my case on AWS RDS it helped to run

**Comment by marcocitus** [comment]
Support for running without doing ALTER EXTENSION is somewhat limited / on a best effort basis.
