### ISSUE TITLE
How to install pg_cron in ubuntu?

### ISSUE THREAD

**Issue by donatello** [citusdata/pg_cron#21]
Any alternative other than building from source?

**Comment by tvarsis** [comment]
Any news on this? Also looking to install on Ubuntu.

**Comment by abcfy2** [comment]
Any updates? Is there any Ubuntu repos?

**Comment by ponach** [comment]
@donatello @tvarsis  @abcfy2  did you manage to install pg_cron on ubuntu ? if so how ? thanks a lot for your time.

**Comment by ehmo** [comment]
It's fairly simple, you just need to do a bit of work on your side.

- Make sure you have installed Postgresql 9.6. You will also need [postgresql-server-9.6](https://www.postgresql.org/download/linux/ubuntu/)
- Clone this repository somewhere on the server with Postgresql
- Then you need to locate the `pg_config`. Should be in `/usr/bin`. If not, try `sudo find / -name 'pg_config' 2>/dev/null`. Once you know where it is, add it to the PATH `export PATH=/usr/bin/:$PATH`
- The you need both `make` and `gcc`, you know the usual `sudo apt install make gcc`
- When all done, then run `make && sudo PATH=$PATH make install`
- If all went through, you need to enable the extension. Edit `/etc/postgresql/9.6/main/postgresql.conf` and add `shared_preload_libraries = 'pg_cron'`
- Restart postgresql
- Connect to the DB via psql as a superuser e.g. `postgres` and activate the extension `CREATE EXTENSION pg_cron;`

All done.

**Comment by jnsone11** [comment]
In addition to @ehmo I had to install pgxs via:
sudo apt-get install postgresql-server-dev-9.6

**Comment by avaczi** [comment]
I am trying to install `pg_cron` for 9.5.  Getting the following error:

```
2017-10-05 16:42:59 CEST [27095-1] FATAL:  incompatible library "/usr/lib/postgresql/9.5/lib/pg_cron.so": version mismatch
2017-10-05 16:42:59 CEST [27095-2] DETAIL:  Server is version 9.5, library is version 9.6.
```
 
How to come around that?

**Comment by ehmo** [comment]
@avaczi it tells you everything in the error message. You have followed my instructions which are based on the version 9.6 however you have version 9.5. So uninstall the libraries you’ve installed and replace 9.6 with 9.5 and it will work.

**Comment by avaczi** [comment]
@ehmo thanks.  I followed the README.md, first installing the 9.6 dev package (for PGXN) accidentally.  Built `pg_cron`, then realized I need 9.5 dev, so installed it and tried to rebuild - apparently, only the `make install` did anything.  Now that I realized this, I just removed the source dir, cloned it again and built using 9.5 - it works now.  Sorry for the inconvenience :)

**Comment by ChristophBerg** [comment]
Packages are available on https://apt.postgresql.org now.

**Comment by ehmo** [comment]
Maybe you could update the install section in readme.

**Comment by marcocitus** [comment]
Thanks for releasing the packages!

Updated the readme.
