### ISSUE TITLE
cron.unschedule(jobname) doesn't work

### ISSUE THREAD

**Issue by 1schmnkS** [citusdata/pg_cron#211]
Hello, 

~~~

postgres 14.5 
pg_cron 1.4.2

~~~

Here's my table **cron.job**: 

~~~ 

[local]:5432 postgres@crondb=# select * from cron.job ;
 jobid |  schedule  |    command    | nodename  | nodeport | database | username | active | jobname
-------+------------+---------------+-----------+----------+----------+----------+--------+---------
    17 | 10 * * * * | select now(); | localhost |     5432 | alpaca   | alpaca   | t      | peter
    18 | 10 * * * * | select now(); | localhost |     5432 | alpaca   | alpaca   | t      | peter2
    20 | 10 * * * * | select now(); | localhost |     5432 | alpaca   | alpaca   | t      | peter3
(3 rows)

~~~

When I try to run **unschedule(jobname)** I get the following error: 

~~~

[local]:5432 postgres@crondb=# select cron.unschedule('peter3') ;
ERROR:  could not find valid entry for job 'peter3'

~~~

both unschedule functions are present: 

~~~

[local]:5432 postgres@alpaca=# \df
                                                                                                                  List of functions

... 
 cron   | unschedule           | boolean          | job_id bigint                                              | func
 cron   | unschedule           | boolean          | job_name name                                        | func

... 
(7 rows)

~~~ 
What am I missing?

kr p.

**Comment by darshansh** [comment]
Your syntax seems ok. Could you please check if any space in job name ?  I checked, if there is no entry for job name then only it gives error.

**Comment by 1schmnkS** [comment]
Sry for the late reply. 

I checked the jobnames for *spaces*: 

# select jobname , length(jobname) from job ;

│ jobname │ length │
│ peter       │      5 │
│ peter2     │      6 │
│ peter3     │      6 │

(3 rows)

# select cron.unschedule('peter3') ;
ERROR:  could not find valid entry for job 'peter3'

**Comment by slightwv** [comment]
I was able to reproduce what you are seeing as well.  This doesn't even make 100% sense to me but I sort of understand it.

What user are you logged into the postgres database as?  If it isn't alpaca, you'll get this error since you aren't the user that 'owns' the job.

If you call the unschedule version using the jobid, it will work:
select cron.unschedule(20) ;

Well, at least it did on my database.  ;)

**Comment by 1schmnkS** [comment]
$> set role 'alpaca' ;
SET
$> select cron.unschedule('peter3') ;
┌────────────┐
│ unschedule │
├────────────┤
│ t          │
└────────────┘
(1 row)

case closed ;) Thank's for your support
