### ISSUE TITLE
cron job 1 connection failed : could not receive data from client: Connection reset by peer

### ISSUE THREAD

**Issue by osimarmedeiros** [citusdata/pg_cron#23]
Hi. 

I'm running postgres 9.6 and I have configured pg_cron in accordance with your guide.
I also have set a cron job to run by the minute, so I could test it and remove my Linux cron.

But I am stuck with this error :

< 2017-03-15 11:58:00.000 UTC > LOG:  cron job 1 starting: SELECT unilever_data_merge('unl_client')
< 2017-03-15 11:58:00.016 UTC > LOG:  cron job 1 connection failed
< 2017-03-15 11:58:00.016 UTC > LOG:  could not receive data from client: Connection reset by peer

This is my cron.job table content :

unilever=# SELECT * FROM cron.job ;
 jobid | schedule  |                 command                  | nodename  | nodeport | database | username 
-------+-----------+------------------------------------------+-----------+----------+----------+----------
     1 | * * * * * | SELECT unilever_data_merge('unl_client') | localhost |     5432 | unilever | unilever

If I run this function with this user from localhost, via psql client, it goes smooth :

[root@unilever-teste1 ~]# psql -U unilever -h localhost -d unilever -c "SELECT unilever_data_merge('unl_client')"
NOTICE:  2017-03-15 12:00:19.833+00 Starting execution.  
NOTICE:  Table: unl_client, query type: Insert, query order: 1
NOTICE:  Execution time : 1 seconds. Affected row(s): 0.  
NOTICE:  Table: unl_client, query type: Update, query order: 2
NOTICE:  Execution time : 0 seconds. Affected row(s): 0.  
NOTICE:  Table: unl_client, query type: Update, query order: 3
NOTICE:  Execution time : 0 seconds. Affected row(s): 0.  
NOTICE:  2017-03-15 12:00:21.715+00 Finished execution.  

What could be causing this issue ?

Thanks !

**Comment by marcocitus** [comment]
Just to sanity check, what's the value of `listen_addresses` and the contents of `pg_hba.conf`?

**Comment by osimarmedeiros** [comment]
These are some postgresql.conf settings [the ones that matter] :

listen_addresses = '*'
max_connections = 100
ssl = on
shared_buffers = 128MB
dynamic_shared_memory_type = posix  
shared_preload_libraries = 'pg_cron'
cron.database_name = 'unilever'


And these are pg_hba.conf settings :

local      all                      all                                       trust
host       replication         all              127.0.0.1/32     trust
host       replication         all              ::1/128              trust
host       all                      all              127.0.0.1/32     md5
host       all                      all              ::1/128              md5
host       all                      pgadmin    0.0.0.0/0           md5
host       template0          all             0.0.0.0/0            reject
host       template1          all             0.0.0.0/0            reject
hostssl  all                       all             0.0.0.0/0            md5
host      all                       all             0.0.0.0/0            reject

**Comment by marcocitus** [comment]
I think this happens because connections from 127.0.0.1 require a password. You can either do `UPDATE cron.job SET nodename = ''` to use a unix domain socket for which you have trust authentication enabled, or create a .pgpass file in the home directory of the postgres user to supply a password to pg_cron.

We should probably start using unix domain sockets by default. I was a bit hesitant to allow non-privileged users to run queries via a unix domain socket, but I can't think of any major downsides right now.

**Comment by osimarmedeiros** [comment]
Thanks @marcocitus ! Setting nodename to '' did the trick.
I prefer that over the .pgpass alternative.

Thanks !
```

< 2017-03-15 17:48:00.000 UTC > LOG:  cron job 2 starting: SELECT unilever_data_merge('unl_client')
NOTICE:  2017-03-15 17:48:00.007+00 Starting execution.  

NOTICE:  Table: unl_client, query type: Insert, query order: 1
NOTICE:  Execution time : 1 seconds. Affected row(s): 0.  

NOTICE:  Table: unl_client, query type: Update, query order: 2
NOTICE:  Execution time : 0 seconds. Affected row(s): 0.  

NOTICE:  Table: unl_client, query type: Update, query order: 3
NOTICE:  Execution time : 0 seconds. Affected row(s): 0.  

NOTICE:  2017-03-15 17:48:01.885+00 Finished execution.  

< 2017-03-15 17:48:01.986 UTC > LOG:  cron job 2 completed: 1 row

```
