### ISSUE TITLE
Not able to call procedures with transaction control in it

### ISSUE THREAD

**Issue by fourvees** [citusdata/pg_cron#230]
Hi All,

Though PGSQL allows subtransactions since v11.0 in procedures, we are unable to use them in pg_cron as it begins a transaction. Thus, it would be useful if pg_cron provides a config to turn on/off autocommit for cron jobs. 

Thanks in advance.

**Comment by fourvees** [comment]
This is working as expected and thus closing it as a non issue.

**Comment by marcocitus** [comment]
You can use procedures to do multiple separate transactions
https://www.postgresql.org/docs/current/sql-createprocedure.html
