### ISSUE TITLE
Add pg_cron 1.3+ for Ubuntu 20.04 LTS + Postgres 12

### ISSUE THREAD

**Issue by mysterious-ben** [citusdata/pg_cron#234]
**Issue:**
The latest version for Ubuntu 20.04 LTS + PostgreSQL 12 is pg_cron 1.2 (installed via `sudo apt install postgresql-12-cron`).

This is problematic because the newest pg_cron functionality (such as job names) is not available.

Building from source fails as well:
`make && sudo PATH=$PATH make install`
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/pg_cron.o src/pg_cron.c
src/pg_cron.c:14:10: fatal error: sys/resource.h: No such file or directory
   14 | #include <sys/resource.h>
      |          ^~~~~~~~~~~~~~~~
```

**Possible solution:**
Add pg_cron 1.3+ to the package postgresql-12-cron.
Alternatively, give a suggestion how to build it from source on Ubuntu 20.04 LTS.

**Comment by marcocitus** [comment]
That probably depends on the package maintainer, but you should be able to get a recent version from:
https://packagecloud.io/citusdata/community/packages/ubuntu/focal/postgresql-12-pgcron_1.4.2.citus-1_amd64.deb?distro_version_id=210
