### ISSUE TITLE
Add a way to "name" a job and then update the schedule for that specific job

### ISSUE THREAD

**Issue by sarus** [citusdata/pg_cron#24]
We have a use case where we want to be able to update a job's schedule based on a job's name (i.e., a fixed attribute that is set from a static config rather than a dynamic ID value).

I think it would be really useful to add an optional unique "job_name" column that would allow jobs to be referenced by a static string.

So something like:

```
SELECT cron.schedule('updateStats', '0 * * * *', 'REFRESH MATERIALIZED VIEW CONCURRENTLY user_stats');
```

Then have an ability to do something like:

```
SELECT cron.updateSchedule('updateStats', '0 1 * * *');
```

Thanks!

**Comment by sarus** [comment]
Actually I'm silly as we could just manually update based on the query being run.  That being said being able to name the job would probably be a little cleaner.

**Comment by mlegenhausen** [comment]
For everyone can't wait for the feature here is the necessary code for creating unique optional named jobs. I also tried to alter the `cron.job` table but that leads to crashes inside the C code.

Creating a `updateSchedule` function could be implemented by removing and readding the schedule.

```sql
BEGIN;

SET client_min_messages = warning;

CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE TABLE cron.job_name (
  id serial PRIMARY KEY,
  jobid bigint REFERENCES cron.job (jobid),
  name text NOT NULL UNIQUE
);

CREATE OR REPLACE FUNCTION cron.schedule_named(
  name text,
  schedule text,
  command text
) RETURNS bigint AS $$
#variable_conflict use_variable
DECLARE
  result bigint;
BEGIN
  SELECT cron.schedule(schedule, command) INTO result;
  INSERT INTO cron.job_name (jobid, name) VALUES (result, name);
  RETURN result;
END;
$$ LANGUAGE plpgsql STRICT SECURITY DEFINER;

CREATE OR REPLACE FUNCTION cron.unschedule_named(
  name text
) RETURNS boolean AS $$
#variable_conflict use_variable
DECLARE
  jobid bigint;
  result boolean;
BEGIN
  SELECT j.jobid INTO jobid
    FROM cron.job_name j
    WHERE j.name = name;

  IF jobid IS NULL THEN
    RAISE EXCEPTION 'Unknown job with name %', name;
  END IF;

  SELECT cron.unschedule(jobid) INTO result;

  IF result = true THEN
    DELETE FROM cron.job_name WHERE jobid = jobid;
  END IF;

  RETURN result;
END;
$$ LANGUAGE plpgsql STRICT SECURITY DEFINER;

COMMIT;
```

One thing that make this feature very useful is when you want to control the cron job creation by migration scripts. Finding out the right jobid for unschedule is with a name much easier.

**Comment by marcocitus** [comment]
The https://github.com/citusdata/pg_cron/tree/beta-2.0 branch includes an optional job name.

**Comment by esatterwhite** [comment]
It would be great to get this in a release. Any progress on this front?
