### ISSUE TITLE
Run cron outside a single transaction

### ISSUE THREAD

**Issue by Navbryce** [citusdata/pg_cron#244]
Is there anyway to run a pg_cron job outside a transaction? I'm trying to do read from a table then do a concurrent index build. Postgres won't allow any other statements to be run in the same txn block as a concurrent index build.

**Comment by marcocitus** [comment]
Not directly. Most of the time you could use a procedure, but in case of CREATE INDEX CONCURRENTLY you'd have to use something like dblink to connect back to the database server.

**Comment by Navbryce** [comment]
Makes sense! Yes, that was something I was considering. Thanks for the help!
