### ISSUE TITLE
pg_cron frequent schedule at minute or hourly but not at 00

### ISSUE THREAD

**Issue by koureasstavros** [citusdata/pg_cron#255]
While using pg_cron we can schedule jobs to run every 10 minutes (*/10 * * * *), that means, each job given the current hour (10:00) will run at:

-10:10
-10:20
-10:30
-etc

If we have 500 jobs, then all these jobs will start in parallel stretching a lot the underlaying infrastructure., now if we do not care about the parallel start, it make sense to start job at the moment of the schedule and repeat that job based on the job schedule.

Job1
-10:10
-10:20
-10:30

Job2
-10:11
-10:21
-10:31

Job3
-10:12
-10:22
-10:32

Is that possible?

**Comment by df7cb** [comment]
`1-59/10 * * * *`
