### ISSUE TITLE
Run a job every x seconds

### ISSUE THREAD

**Issue by Eric-zch** [citusdata/pg_cron#256]
Could pg_cron support running a job every x seconds? Currently I use pg_dbms_job to support this requirement.
Hope pg_cron can also support it.
Thank you.

**Comment by Eric-zch** [comment]
@marcocitus 
Thank you so much for your quick response.

**Comment by Eric-zch** [comment]
@marcocitus 
Could I schedule like this way: SELECT cron.schedule('*/5 * * * * 1-5', 'SELECT dostuff()');
I want to run a job from Mon to Fri, every 5 seconds.

**Comment by marcocitus** [comment]
No, though I suppose you could schedule weekly jobs on Monday & Friday that schedule and unschedule the every 5 seconds job.

**Comment by Eric-zch** [comment]
Hi @marcocitus 
Good point, Thank you!
