### ISSUE TITLE
cron.timezone

### ISSUE THREAD

**Issue by 1schmnkS** [citusdata/pg_cron#265]
Hello, 

Quick question: starting with which pg_cron-version/postgres-version cron.timezone is honored? 

I have two installations: 

Postgres 14: 

`=> select * from pg_available_extensions where name = 'pg_cron' ;

│ pg_cron │ 1.4-1           │ 1.4-1             │ Job scheduler for PostgreSQL │

(1 row)`

Postgres 15: 

`select * from pg_available_extensions where name = 'pg_cron' ;

│ pg_cron │ 1.5             │ 1.5               │ Job scheduler for PostgreSQL │

(1 row)`

I added cron.timezone with my timezone to postgresql.conf and restarted both instances but the new timezone-setting only works in the second case.

**Comment by marcocitus** [comment]
That's expected, the feature was added in 1.5

**Comment by 1schmnkS** [comment]
Thank you!
