### ISSUE TITLE
ERROR:  compressed lz4 data is corrupt on big-endian architectures

### ISSUE THREAD

**Issue by df7cb** [citusdata/pg_cron#267]
With pg_cron 1.5.1, all Debian/Ubuntu versions, all big-endian architectures (s390x, hppa, powerpc, ppc64) fail like this:

```
 -- Stop scheduling a job
 SELECT cron.unschedule('myvacuum');
- unschedule 
-------------
- t
-(1 row)
-
+ERROR:  compressed lz4 data is corrupt
```

https://buildd.debian.org/status/logs.php?pkg=pg-cron&ver=1.5.1-1
https://pgdgbuild.dus.dg-i.net/view/Binaries/job/pg-cron-binaries/43/

**Comment by df7cb** [comment]
This was a weird one.

The bug was actually already fixed in the code, and the test code is basically also ok, except that the extension test script chose to test the *1.4* version of the SQL scripts. I've changed it to test the latest version and all tests pass now.

**Comment by nmisch** [comment]
This is not specific to big-endian; it reproduces on x86 as follows:

```
[local] test=# create extension pg_cron version '1.4';
CREATE EXTENSION
[local] test=*# select cron.unschedule(job_name := 'f');
ERROR:  compressed pglz data is corrupt
[local] test=*# select cron.unschedule(job_name := 'cr');
ERROR:  could not open relation with OID 16430
[local] test=*# select cron.unschedule(job_name := 'jr');
ERROR:  compressed pglz data is corrupt
[local] test=*# select cron.unschedule(job_name := 'ks');
ERROR:  could not open relation with OID 16430
```

It began when commit 6fc9ca9 changed a parameter of type `name` to type `text`
without changing the C symbol.  The PostgreSQL-recommended way to handle this
would be to introduce a new C symbol like cron_unschedule_named_text() for the
new signature, then keep cron_unschedule_named() expecting the old signature.
(It could convert the argument to text and call cron_unschedule_named_text().)

I don't know a way to improve things at this point.  Changing
cron_unschedule_named() to once again work with `VERSION '1.4'` would break
`VERSION '1.5'` installations.
