### ISSUE TITLE
Pg_cron crontab log 

### ISSUE THREAD

**Issue by martinamuscariello** [citusdata/pg_cron#27]
We're trying to configure periodic jobs in PostgreSQL.
To do this, we installed on Linux machine, with Postgres 9.6 running, the pg_cron project.

System information:

OS: Linux pg 4.4.0-72-generic #93-Ubuntu SMP
PG: Postgres 9.6.3 installed from repo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'

Following the instructions in the pg_cron repository, we set in postgresql.conf the configuration below:

shared_preload_libraries = 'pg_cron'   
cron.database_name = 'our db_name'

Then, on db_name, we created the EXTENSION pg_cron

CREATE EXTENSION pg_cron;
and we scheduled our first Postgres job:

SELECT cron.schedule('45 12 * * *', $$CREATE TABLE schema.testCron AS Select 'Test Cron' as Cron$$);
So, jobid 1 was created and listed in table cron.job.

We expected that at 12:45 the command of the scheduled job would have been launched. But nothing happened.

The testCron table was not created and we had no trace in any logs.

We also defined LOG_FILE in /usr/src/pg_cron/include/pathnames.h to enable logging.

But, after re-compiling the project and restarting the Postgres service, we did not track log for pg_cron.

How can we enable logs for pg_cron to check scheduling result?

Thanks in advance!

**Comment by marcocitus** [comment]
The most common reason for not seeing job run at the expected time is that schedule is in UTC, regardless of the system timezone. You can use `SELECT now() at time zone 'utc'` to see the current time in UTC, or run `date -u`.

The `cron.log_statement` setting controls whether a job is logged. It is on by default.

**Comment by martinamuscariello** [comment]
Ok, there is a time difference, but we still do not see the table created. 
We scheduled a new job. More then four hours have passed since schedule time .
Where can we check scheduling result ?

**Comment by marcocitus** [comment]
What time zone are you in?

As a basic sanity check to see if logging is enabled, you can run `SELECT cron.schedule('* * * * *', 'SELECT 1')` which will run `SELECT 1` at the start of every minute and should show up in the log.

**Comment by martinamuscariello** [comment]
We are in GMT zone.
Where can we find the log file ?

**Comment by marcocitus** [comment]
In the regular postgres log.

**Comment by martinamuscariello** [comment]
In postgres log we find 

2017-06-19 15:44:00.000 CEST [11353] LOG:  cron job 3 starting: SELECT 1
2017-06-19 15:44:00.007 CEST [11353] LOG:  cron job 3 connection failed
2017-06-19 15:44:00.007 CEST [11372] postgres@agile-h726 LOG:  could not receive data from client: connection reset by peer

Below our pg_hba configuration

# TYPE  DATABASE        USER            ADDRESS                 METHOD
host all all 192.168.0.0/23 trust
# "local" is for Unix domain socket connections only
local   all             all                                     peer
local   agile-h726      postgres                   trust         #enable trust authentication for the user running the cron job

What are we wrong?

**Comment by marcocitus** [comment]
You'll need to either run `UPDATE cron.job SET nodename = ''` to allow pg_cron to connect via a `local` connection or add `host all all 127.0.0.1/32` to allow access to the pg_cron background worker.

**Comment by martinamuscariello** [comment]
Thanks a lot.
All work now. 

I close Issue.
