### ISSUE TITLE
Not necessary to save user`s password in task?

### ISSUE THREAD

**Issue by roseduan** [citusdata/pg_cron#276]
I found that the password is not saved in task, but we should connect to postgres by the user, how does it success?

**Comment by marcocitus** [comment]
It mainly depends on pg_hba.conf.

There are a few different ways in which pg_cron can be configured:
1. Use TCP/IP to localhost (the default)
2. Use Unix domain socket by setting `cron.host = <unix domain socket directory>`
3. Use `cron.use_background_workers = on`

For #1 & #2, if local connections are set to `trust` in `pg_hba.conf`, then no password is required. If it is set to md5/scram-sha-256, you need a `.pgpass` file in the home directory of the Linux user that runs postgres.

For #3 no authentication is required, though you usually cannot run as many background workers concurrently.

**Comment by roseduan** [comment]
Thanks
