### ISSUE TITLE
Is it wrong to have a lot of cron jobs (over a million)?

### ISSUE THREAD

**Issue by tolunayar** [citusdata/pg_cron#278]
I use postgres. In my application I create for each user an own cron job which runs every 24h and checks whether something is fulfilled or not and then do something accordingly. I cannot create just one cron job and check dynamically according to the id of the user whether something is fulfilled or not because the starting date time of 24h is not static but dynamic according to the user input, (one user wants to start at 4 p.m. to other at 8 p.m. to count 24h).

Is there anything wrong with having millions of jobs even if it makes sense? Are there any concerns? For example regarding performance, etc? Thanks..

**Comment by marcocitus** [comment]
Fwiw, the number of jobs that run concurrently is capped to cron.max_running_jobs, and beyond that jobs are queued.

As to whether it causes issues, I'm not sure. Worth doing some tests.

**Comment by tolunayar** [comment]
In Supabase cron.max_running_jobs is fixed on 32. I do not know whether I can increase it. Anyways, I think I have to think about an alternative approach since cron jobs are in postgres capped to the cron.max_running_jobs in any case..

**Comment by tolunayar** [comment]
Is it possible to increate cron.max_running_jobs ?
