### ISSUE TITLE
Call Remote Procedure

### ISSUE THREAD

**Issue by YuriyTigiev** [citusdata/pg_cron#279]
Hello, 

How to Call Remote Procedure via a dblink ?

SELECT cron.schedule('schedule_delete_old_ohlcv_history_data_on_adca2_dev', '1,6,11,16,21,26,31,36,41,46,51,56 * * * *', $$SELECT dblink_exec('dblink2_dev', 'CALL public.delete_old__data()');$$);

**Comment by marcocitus** [comment]
`select * from dblink('host=localhost port=5432' ,'call delete_old__data()') as res (res text);`
