### ISSUE TITLE
Jobs don't run at specified time

### ISSUE THREAD

**Issue by andrerjesus** [citusdata/pg_cron#29]
I just installed pg_cron and it all seems ok but I can't set specified times to run my jobs.

If I set:
select cron.schedule ('*/1 * * * *', $$insert into test (text) values (current_timestamp)$$);
It works

If i set a fixed time:
select cron.schedule ('30 15 * * *', $$insert into test (text) values (current_timestamp)$$);
Nothing happens. 

Am I missing something?

**Comment by marcocitus** [comment]
A common reason for this is that the schedules use GMT, so if your system uses a different timezone then the query might not run at the expected time.

**Comment by andrerjesus** [comment]
You're right, I didn't pay attention to it. I just compensate the time difference and it worked great. Thank you.

**Comment by gonxalo2000** [comment]
Any chance to change this behavior? Or at least let it documented!? It's very unclear. 
This issue is the only reference i found about it.
Why don't it use the system date/time!?

tks!
