### ISSUE TITLE
Schedule running the day before

### ISSUE THREAD

**Issue by elkejava** [citusdata/pg_cron#290]
EDIT
Since we upgraded debian bullseye and rebooted the DB server past tuesday, it seems that pg_cron does not share the system/postgresql date. 
The time is UTC as usual, but jobs are run one day before.
I noticed it today with a job which is scheduled since a long time for monday, and run last time monday 9th : it run today (sunday). 
I tested with fresh jobs 
scheduled for monday, it ran today (sunday) at the specified time
scheduled for october 15th -> did not run
scheduled for october 16th -> it ran at today (october 15th) the specified time. 
versions are:  
postgresql-12                   12.16-1.pgdg110+1    
postgresql-12-cron              1.6.0-1.pgdg110+1                
server: debian 11, Kernel version 5.10.0-26-amd64

Meanwhile I reproduced the issue on my test server (same versions of all software) where I freshly installed pg_cron. 
alls jobs run one day earlier at UTC time, exactly as on the productive server. setting cron.timezone in postgresql.conf either to GMT or to CEST (which my servers are using) had no effect.

**Comment by elkejava** [comment]
After checking out that 
- the problem persists also when upgrading to postgresql 13
- the package version in debian is the same  for postgresql-12-cron, postgresql-13-cron ,  postgresql-16-cron
I found  a workaround : setting cron.timezone to 'GMT+24' fixes the issue for the moment. So I can wait until debian will publish a corrected package.

**Comment by iglesiasroberto14** [comment]
Seems to be the same problem I'm having in https://github.com/citusdata/pg_cron/issues/288

We used different POV to say before/after but the problem is the same.

**Scheduling a job for day `N` will run on day `N-1`.**

**Comment by elkejava** [comment]
So hopefully the workaround I found works for you! We implemented in the productive setting this morning and it works fine, no  need to adapt the schedules until a corrected version of the package will be published.

**Comment by iglesiasroberto14** [comment]
> So hopefully the workaround I found works for you! We implemented in the productive setting this morning and it works fine, no need to adapt the schedules until a corrected version of the package will be published.

Did you find any bug in the code? what pg_cron version were you running before this issue came up?

**Comment by elkejava** [comment]
grep 'cron' /var/log/dpkg.log*
/var/log/dpkg.log:2023-10-10 12:06:29 upgrade postgresql-12-cron:amd64 1.5.2-2.pgdg110+2 1.6.0-1.pgdg110+1
(all versions coming from the stream of debian 11 - the previous worked with correct day). I did not inspect the code.

**Comment by iglesiasroberto14** [comment]
@elkejava your workaround works. I had to set `cron.timezone="GMT+27"` instead of `GMT-3`

**Comment by elkejava** [comment]
this is great to hear, thank you for posting. Will you have a look in the code?

**Comment by iglesiasroberto14** [comment]
Yes, but couldn't find the problem. I didn't put a lot of time on it

**Comment by marcoslot** [comment]
Thanks for reporting, there was a bug in the way pg_localtime was called introduced in 1.6.0
