### ISSUE TITLE
Call a function via pg_cron

### ISSUE THREAD

**Issue by peZhmanP** [citusdata/pg_cron#30]
Hi

I added a new record in cron.job table via this sql command:

SELECT cron.schedule('* * * * *', 'select "sample_func"(200::INTEGER)');

The pg_cron extension is installed on a db except postgres(sample_db). So cron.database_name in postgresql.conf is set to sample_db

cron.database_name = 'sample_db'

The cron is run every minute, but the problem is that calling this cron caused an error:

< 2017-07-10 22:37:00.001 EDT > LOG:  cron job 10 starting: select "sample_func"(200::INTEGER)
< 2017-07-10 22:37:00.033 EDT > LOG:  cron job 10 connection failed

This is necessary to say that if exist another records in cron.job table in my case, this error is repeated for them. (commands like VACUUM or select 1)

**Comment by marcocitus** [comment]
Most likely you need to give pg_cron permission to access your database via one of the methods mentioned in the readme.

You may be able to resolve it by running `UPDATE cron.job SET nodename = ''` to connect via unix domain socket.
