### ISSUE TITLE
pg_cron is cannot work 

### ISSUE THREAD

**Issue by sangli00** [citusdata/pg_cron#31]
configure 
```
shared_preload_libraries= 'pg_cron,others extension'
cron.database_name='postgres'
```

```
postgres=# select * from cron.job;
 jobid |  schedule   |           command           | nodename  | nodeport | database | username
-------+-------------+-----------------------------+-----------+----------+----------+----------
     1 | */1 * * * * | insert into t1 select now() | localhost |     5432 | postgres | postgres
(1 row)
```

backend ground is OK
```bgworker: pg_cron_scheduler```
Why job is cant work? PG version is 9.5.3

**Comment by marcocitus** [comment]
Did you check the log? Most likely you need to give pg_cron permission to access your database.

You may be able to resolve it by running `UPDATE cron.job SET nodename = ''` to connect via unix domain socket.

**Comment by sangli00** [comment]
OK,I executor sql ```UPDATE cron.job SET nodename = '' ```,pg_cron is OK.
Why need update nodename is ''?
