### ISSUE TITLE
unschedule fails if extension is dropped and recreated between calls

### ISSUE THREAD

**Issue by hari90** [citusdata/pg_cron#344]
```
create extension pg_cron;
select cron.schedule('my-job2', '* * * * *', 'VACUUM');
select cron.unschedule(1);
drop extension pg_cron;
create extension pg_cron;
select cron.schedule('my-job2', '* * * * *', 'VACUUM');
select cron.unschedule(1);
```

Fails with

> ERROR:  could not open relation with OID 16967

This is because `unschedule` and `unschedule_named` use `CronJobRelationId()` which caches the `CachedCronJobRelationId` on the user connection. This connection does not register for cache invalidations so this value is not cleared when the extension is dropped.

**Comment by marcoslot** [comment]
Fixed by #346
