### ISSUE TITLE
Does the PG_CRON support PG 17 major version? 

### ISSUE THREAD

**Issue by jasonchenTJ** [citusdata/pg_cron#359]
Hi Guys,

Currently we are using PG 16.4 with pg_cron 1.6.2. That's works very well! 
We are going to update the PG major version to 17, can we still using the pg_cron version 1.6.2? 
or we need to update the extension to last release version? 

Thanks
Jason

**Comment by esiaero** [comment]
To add on, pg_cron is compatible to build with PG 17 of 1.6.3 (https://github.com/citusdata/pg_cron/releases/tag/v1.6.3).
