### ISSUE TITLE
Can not create extension

### ISSUE THREAD

**Issue by carapai** [citusdata/pg_cron#37]
When I try to create extension on the database this is the error that I get
```
CREATE EXTENSION pg_cron;
```
ERROR:  unrecognized configuration parameter "cron.database_name"
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF

**Comment by marcocitus** [comment]
You need add pg_cron to shared_preload_libraries in postgresql.conf and restart postgres.

**Comment by carapai** [comment]
Thank you @marcocitus,
It worked

**Comment by abrigeiro** [comment]
Hello, I'm having a similar problem, I have a Docker File based on postgres:10.1-alpine, I manage to install the pg_cron extension, but now I'm unnable to change the postgresql.conf, so I tried to use the following instruction;

ALTER SYSTEM SET shared_preload_libraries = 'pg_cron';

but yet I still have the same error.

**Comment by marcocitus** [comment]
@abrigeiro can you restart postgresql in a way that preserves the setting?

**Comment by abrigeiro** [comment]
My objective would be that when I start the Docker it would create everything needed to work, so I was trying to do everything on the Dockerfile. I did try to change the configuration file directly on the image I was successful but when I restart the file changes to default values again.

**Comment by disarticulate** [comment]
@abrigeiro 

I spent too much time on this, but in Docker (dockerhub's standard postgres) I do the following 

Dockerfile:
`
...
COPY postgresql.conf /var/lib/postgresql/postgresql.conf
COPY 000000-restart.pg.sh /docker-entrypoint-initdb.d/0000000.sh
`
000000-restart.pg.sh
`
#!/bin/bash
cp /var/lib/postgresql/postgresql-dev.conf $PGDATA/postgresql.conf
psql -c "CREATE DATABASE cron_database;"
/usr/lib/postgresql/10/bin/pg_ctl restart
`

So in the dockerfile we copy in the standard lib directory our custom postgresql.conf

Then we copy over our startup script, noting that 000000.sh will make it start first when the normal Docker postgres startsup.

That script replaces the conf created by initdb, creates the database_name required by `cron.database_name` and has the `shared_preload_libraries = 'pg_cron'` then restarts the database using pg_ctl

Then the rest of the files run in the standard docker init (https://hub.docker.com/_/postgres/)

**Comment by ahonnecke** [comment]
@disarticulate 
Would you be willing to share the altered Dockerfile that you're using with me?

Thanks!
