### ISSUE TITLE
Warning being treated as Error in ManageCronTask function

### ISSUE THREAD

**Issue by npchowdr** [citusdata/pg_cron#373]
I am getting the following error after latest commit https://github.com/citusdata/pg_cron/commit/18e79f95d2a01277304c75ecdab54778b7f9e26f

0.642 src/pg_cron.c: In function ‘ManageCronTask’:
0.642 src/pg_cron.c:1650:25: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
0.642  1650 |                         char *command = cronJob->command;
0.642       |                         ^~~~
0.838 cc1: all warnings being treated as errors
0.840 make: *** [<builtin>: src/pg_cron.o] Error 1

**Comment by marcoslot** [comment]
Seems already fixed by https://github.com/citusdata/pg_cron/commit/18e79f95d2a01277304c75ecdab54778b7f9e26f
