### ISSUE TITLE
Can pg_cron be used with streaming replication?

### ISSUE THREAD

**Issue by michelp** [citusdata/pg_cron#38]
I have a primary database that is streaming to a hot-standby replica.  I'd like to use pg_cron, but I'm thinking about the issues related to failover.  It seems like the right behavior  would be for pg_cron's worker to be running on the primary, but either absent entirely from, or 'paused' on the replica until triggered by the failover event.  Is this possible?

**Comment by marcocitus** [comment]
Yep, that's the default and only behaviour. You'll want to make sure it's in shared_preload_libraries on both primary and standby.

**Comment by michelp** [comment]
Thank you!
