### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by bearrito** [citusdata/pg_cron#41]
I'm trying to understand if pg_cron is suitable for my needs and so want to clarify some items from documentation.

In particular

`By default, the pg_cron background worker expects its metadata tables to be created in the "postgres" database.` Does this really mean database and not schema?

My setup is as follows

1. Hot-Warm Cluster
2. N databases on the nodes
3. Each databases has 2 schemas (public and app)

Is pg_cron suitable for my setup e.g. multi-tenant nothing shared ? 

If it is suitable I'm assuming that I'll end up with N pg_cron schemas and N cron.job tables? Is that correct?

Thank you.

**Comment by marcocitus** [comment]
The `pg_cron` metadata needs to be in one particular database and that is the only database in from you can schedule jobs, but it can actually run jobs in any database if you manually modify the `cron.job` table.

For instance:
```
$ psql -d postgres
Timing is on.
psql (10.0)
Type "help" for help.

postgres=# INSERT INTO cron.job (schedule, command, database) VALUES ('* * * * *', 'VACUUM public.data', 'mytenant');
INSERT 0 1
Time: 6.083 ms
postgres=# SELECT * FROM cron.job;
 jobid | schedule  |      command       | nodename | nodeport | database | username | jobname 
-------+-----------+--------------------+----------+----------+----------+----------+---------
     1 | * * * * * | VACUUM public.data |          |     5432 | mytenant | marco    | 
(1 row)
```

**Comment by bearrito** [comment]
Okay. That makes sense. Thanks for the quick response.
I think this  issue can be closed.
