### ISSUE TITLE
Clarification required pg_cron scheduling for long running jobs 

### ISSUE THREAD

**Issue by sandeep048** [citusdata/pg_cron#44]
Say there is a materialized view that is built on top of mysql_fdw which gets refreshed every minute,
If the refresh takes more than a minute to execute what is the default behaviour of pg_cron?

- The job gets silently killed (since the previous op didn't finish.) The job will get rescheduled anyway. 
- The job get queued => this saturated all available postgres connections on my machine when I tried with manual crontab not pg_cron?

**Comment by marcocitus** [comment]
The job gets queued, but will not start until the current run has finished. It keeps a counter of how many times it should have started and keeps repeating until the counter reaches 0 (unless the server restarts).

**Comment by sandeep048** [comment]
Brilliant this is exactly what I am looking for 😎
