### ISSUE TITLE
Installing pg_cron

### ISSUE THREAD

**Issue by JayeshDAVE** [citusdata/pg_cron#45]
Hello:

I need some clarity about installing pg_cron on AWS Aurora Postgresql cluster (multi node).

Not sure if there is any other way to connect to instance using PUTTY and i am not able to do that.

Installation instruction are simple of here but not is respect to AWS Aurora Postgresql cluster and how to do that.

Please help if you can.

Thanking in advance.

**Comment by marcocitus** [comment]
You typically cannot install your own extensions in managed postgres services, so you'd have to ask Amazon to make pg_cron available.

Citus Cloud does have pg_cron installed: https://www.citusdata.com/product/cloud
