### ISSUE TITLE
Not able to make pg_cron work

### ISSUE THREAD

**Issue by ranjanprj** [citusdata/pg_cron#48]
This seems to be a very useful project and appreciate Citusdata opensourcing it.
I have tried this in both 9.6 and 10 ( single node default installation )  and did exactly as the instructions have said, but after several hours I cannot seem to make it work in both cases.

Environment:
Plain vanilla installation of PG 9.6 and PG 10 on Ubuntu

1. I create a testcron table with id int , insert_time timestampz default now()
2. I create a cron job using the syntax with 
SELECT cron.schedule('1 * * * *', $$insert into testcron values(1)$$);
or 
SELECT cron.schedule('1 * * * *', $$delete from testcron where id = 1$$);
3. It creates the job but doesn't do anything after 1 minute.

**Comment by marcocitus** [comment]
You may want to check the postgres log for authentication problems. For pg_cron to work, postgres needs to allow TCP connections from localhost.

You can also try switching to unix domain sockets by running:
```sql
UPDATE cron.job SET nodename = '';
```

**Comment by ranjanprj** [comment]
I tried everything from modifying pg_hba.conf to trust for localhost and creating a .pgpass file but
UPDATE cron.job SET nodename = ''; worked for me.

Thanks

**Comment by gworley3** [comment]
I'm running into similar issues myself. I tried the suggested UPDATE but that didn't help, and I'm still not able to make any jobs run. I see nothing in the log about it other than this on startup:

```
2018-05-21 20:21:36.164 UTC [10109] LOG:  pg_cron scheduler started
2018-05-21 20:21:36.630 UTC [10110] [unknown]@[unknown] LOG:  incomplete startup packet
```

Running Postgres 9.6 for what it's worth.

**Comment by ranjanprj** [comment]
Not sure but try setting it to - 
`UPDATE cron.job SET nodename = ''127.0.0.1; `

**Comment by marcocitus** [comment]
> Is this mandatory to set nodename to '' for this work locally ?

No, but pg_cron somehow needs to be able to connect back to postgres in order to run commands. By default it tries to connect to `localhost` over TCP. Your `pg_hba.conf` and `.pgpass` need to be set up to allow that. If you set `nodename` to an empty string it starts using unix domain socket instead.

> `SELECT cron.schedule('1 * * * *', $$delete from testcron where id = 1$$);`
> It creates the job but doesn't do anything after 1 minute.

Note that the semantics of the schedule is that it runs on the first minute of the hour, not every minute.

**Comment by marcocitus** [comment]
> I see nothing in the log about it other than this on startup:
> `2018-05-21 20:21:36.164 UTC [10109] LOG:  pg_cron scheduler started`

That seems fine. Once your job is scheduled to run there should be some error if it is unable to connect.

**Comment by cosmindidis** [comment]
For what is worth: my v1.1 installation (built from sources) has the 'active' column in 'job' table set to false for all jobs. Updating it to true did the trick, after trying/checking everything else (including changing the nodename to '127.0.0.1').

**Comment by marcocitus** [comment]
Uff, thanks for reporting. Fixed this on master.

**Comment by MiguelGuzmanDev** [comment]
> Es posible que desee verificar el registro de Postgres para detectar problemas de autenticación. Para que pg_cron funcione, postgres necesita permitir conexiones TCP desde localhost.
> 
> También puede intentar cambiar a sockets de dominio de Unix ejecutando:
> 
> ```sql
> UPDATE cron.job SET nodename = '';
> ```

Esto funciono para mi

**Comment by emersonmartins8** [comment]
I had this problem, but I fixed it with adjust in pg_hba.conf file.

host    all             all             127.0.0.1/32            trust

**LOG:** /var/log/postgresql/postgresql-17-main.log

2026-06-03 07:30:00.002 -03 [1941350] LOG:  cron job 1 starting: SELECT refresh_all_ponto_views_with_log();
2026-06-03 07:30:10.785 -03 [1941350] LOG:  cron job 1 completed: 1 row
