### ISSUE TITLE
docs suggest wrong location for .pgpass

### ISSUE THREAD

**Issue by adunstan** [citusdata/pg_cron#5]
The README says: "Alternatively, you can create a .pgpass file in the working directory of the database server." But that's not where libpq looks for .pgpass - by default it it looks in the home directory of the user, in this case the user that's running Postgres (or %APPDATA%\postgresql\pgpass.conf  on Windows). Unless I'm misunderstanding the code, that's what the docs should say.

**Comment by marcocitus** [comment]
Thanks for reporting!

**Comment by rmarzocchi84** [comment]
Now @marcocitus has correct the instruction, but for me it not clear. 
FIRST DOUBT: 
The postgresql user is the postgresql role?

SECOND QUESTION:
Normally the postgresql role do not have a home directory in linux.  I need to create a new unix user with the same name of the postgresql role?

Perhaps @adunstan may also help me

**Comment by marcocitus** [comment]
> Normally the postgresql role do not have a home directory in linux.

It's the home directory of whichever linux user is running the postgres server.
