### ISSUE TITLE
ERROR:  invalid schedule: 0 1/4 * * *

### ISSUE THREAD

**Issue by disarticulate** [citusdata/pg_cron#50]
Based on the recommended 

[https://crontab.guru/#0_1/4_*_*_*](https://crontab.guru/#0_1/4_*_*_*)

```
SELECT cron.schedule('0 1/4 * * *', $$
    select replicate_whole_database('192.168.1.220','mydb');
$$);
```
I'm guessing steps are not implemented? I didn't see it in the readme.

**Comment by marcocitus** [comment]
Thanks for reporting. The fine print on crontab.guru mentions "Non standard! May not work with every cron.", I guess pg_cron is one of those crons :).

You can work around it by using `0 1-23/4 * * *`

**Comment by disarticulate** [comment]
I was just following orders:

```
An easy way to create a cron schedule is: crontab.guru.
```
