### ISSUE TITLE
pg_cron schedule didn't work

### ISSUE THREAD

**Issue by 369488685** [citusdata/pg_cron#59]
![image](https://user-images.githubusercontent.com/17146135/45690612-58d3f680-bb89-11e8-8d4b-4a0b11f33483.png)
I have already created schedule successfully,but no result as I wish.
![image](https://user-images.githubusercontent.com/17146135/45690730-99cc0b00-bb89-11e8-8594-5aeed074f6ad.png)
I want know why it didn't work

**Comment by marcocitus** [comment]
Can you check the postgres log? pg_cron may have trouble connecting to postgres. It may help to run `UPDATE cron.job SET nodename = '';` to connect via a unix domain socket.

**Comment by 369488685** [comment]
thank u！it's worked for me~
