### ISSUE TITLE
Where are results of cron schedule saved?

### ISSUE THREAD

**Issue by kernelfreak** [citusdata/pg_cron#60]
Hello,

How can I know that the scheduler I ran was successful, or any kind of logging? Kindly let me know. Thank you. 

Regards,
Akshay S

**Comment by bplainia** [comment]
I just figured this out a couple weeks ago. I found that it logged in the server's log. For me, it was at /var/log/postgresql/postgresql-10-main.log (for at least Ubuntu).

Should look like the following: (Copied from #1)
> 2016-11-10 03:25:00.003 CET LOG:  cron job 1 starting: UPDATE pit SET a = a + 1
> 2016-11-10 03:25:00.026 CET LOG:  cron job 1 completed: UPDATE 0 1

Would be good to have information about logging on the readme.

**Comment by shimaamarzouk** [comment]
I found it at` /usr/local/var/log/postgres.log`
