### ISSUE TITLE
rpm package for PostgreSQL 11

### ISSUE THREAD

**Issue by tr-patrick** [citusdata/pg_cron#65]
We are planning upgrades for PostgreSQL 10 to PostgreSQL 11. 

When will the rpm for pg_cron in combination with PostgreSQL 11 be available?

yum install -y pg_cron_11

Thank you

**Comment by anikin-aa** [comment]
up

**Comment by tr-patrick** [comment]
I'm not seeing it yet

yum list|grep pg_cron
pg_cron_10.x86_64                      1.0.2-1.el7            citusdata_community
pg_cron_10-debuginfo.x86_64            1.0.2-1.el7            citusdata_community
pg_cron_95.x86_64                      1.0.2-1.el7            citusdata_community
pg_cron_95-debuginfo.x86_64            1.0.2-1.el7            citusdata_community
pg_cron_96.x86_64                      1.0.2-1.el7            citusdata_community
pg_cron_96-debuginfo.x86_64            1.0.2-1.el7            citusdata_community

Just added the repository.

**Comment by tr-patrick** [comment]
Working with rpm voor PostgreSQL 11
