### ISSUE TITLE
citus pg_cron cannot execute several sql statements by order in a job

### ISSUE THREAD

**Issue by zjw5121818** [citusdata/pg_cron#67]
Hello，all：
    It seems that citus pg_cron cannot execute several sql  statements by order in one job. My test environment is citus pg_cron + postgres11. First ,I create two UDFs ( f_test1() and  f_test2())
> declare
st integer;
begin
PERFORM pg_sleep(5);
execute 'insert into testx(iname,idate) select ''fun2'',now()';
return 1;
end

> declare
st integer;
begin
execute 'insert into testx(iname,idate) select ''fun1'',now()';
return 1;
end

and I create a table named testx  to store data;
> create table testx(iname text, idate timestamp);

And then I create a job with citus pg_cron,

>     20 | */1 * * * *  |  select f_test1();select f_test2();   | localhost |     9998 | testdb   | test123 | t

but I got the result like this:

>  iname |           idate            
-------+----------------------------
 fun1  | 2018-11-22 11:23:00.005637
 fun2  | 2018-11-22 11:23:00.005637
 fun2  | 2018-11-22 11:22:00.006262
 fun1  | 2018-11-22 11:22:00.006262

and log like this 

> 2018-11-22 11:23:00.000 CST [119756] LOG:  cron job 20 starting:  select f_test1();select f_test2(); 
2018-11-22 11:23:05.016 CST [119756] LOG:  cron job 20 completed: 1 row
2018-11-22 11:23:05.016 CST [119756] LOG:  cron job 20 completed: 1 row

So ,how can I make these two sql statements execute one by one.
I hope got your answer soon,thx

**Comment by marcocitus** [comment]
Both statements are executed, though only the row count of the first is logged.
