### ISSUE TITLE
Segmentation fault in pg_cron_scheduler

### ISSUE THREAD

**Issue by greatvovan** [citusdata/pg_cron#74]
We had a DB crash due to this module. From the log:

> 2019-05-10 13:22:27.359 PDT [1245] LOG:  worker process: pg_cron_scheduler (PID 1480) was terminated by signal 11: Segmentation fault

**Comment by marcocitus** [comment]
Do you know if it was preceeded by a `cron.unschedule`? There was a bug that was fixed in 1.1.4 that sometimes led to a crash after a `cron.unschedule` due to a race condition.

**Comment by greatvovan** [comment]
There were some schedules and unschedules with this function, that was done manually, not sure it could cause race conditions, but who knows...

**Comment by marcocitus** [comment]
I'm going to assume it was fixed by 1.1.4. If not feel free to reopen.
