### ISSUE TITLE
Wrong link in the documentation

### ISSUE THREAD

**Issue by fluca1978** [citusdata/pg_cron#77]
In the documentation README.md the link *Auto-partitioning using pg_partman* is wrong and is pointing to the following item in the bullet list, that is *Computing rollups in an analytical dashboard*. Apparently I cannot find the correct link for the first item, so it could be good to remove it.

**Comment by marcocitus** [comment]
Thanks. Fixed it to point to https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/
