### ISSUE TITLE
Unable to install in a container based on PostgreSQL official Docker

### ISSUE THREAD

**Issue by ziadloo** [citusdata/pg_cron#8]
Hi I'm trying to install your extension on a container based on PostgerSQL [official docker](https://hub.docker.com/_/postgres/) for version 9.5.5 and I'm facing an error I can not resolve myself.

These are the steps I've taken, after starting a vanilla PostrgeSQL 9.5.5:

```
$ apt-get update
$ apt-get install -y git make gcc postgresql-server-dev-9.5
$ git clone https://github.com/citusdata/pg_cron.git
$ cd ./pg_cron
$ PATH=/usr/lib/postgresql/9.5/bin/:$PATH make
```
The path mentioned in the readme, `/usr/local/pgsql/bin/`, does not exist in this container and I assumed it should be pointing to the directory where the postgres executable is located, so I changed it to `/usr/lib/postgresql/9.5/bin/`. At this point I'm facing the following error:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Iinclude -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o src/job_metadata.o src/job_metadata.c
src/job_metadata.c:232:1: error: ‘NextJobId’ was used with no prototype before its definition [-Werror=missing-prototypes]
 NextJobId(void)
 ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'src/job_metadata.o' failed
make: *** [src/job_metadata.o] Error 1
```

It would be great if you can help me install your extension on a docker. Thanks.

**Comment by ziadloo** [comment]
As it turned out there's a problem with the source, file **job_metadata.c**:**57** should be:

`
static int64 NextJobId(void);
`

instead of:

`
static int64 NextJobId();
`

**Comment by marcocitus** [comment]
Thanks for reporting! This is now fixed on master.
