### ISSUE TITLE
How to run pg_cron in postgresql replication environment

### ISSUE THREAD

**Issue by p0mp0k0** [citusdata/pg_cron#84]
Hi,
I want to run pg_cron in postgresql stream replication environment with 3 service, at default one is master and the others are standby, so how to setup the pg_cron with failover.
thansk.

**Comment by marcocitus** [comment]
Nothing special. Just make sure it's in shared_preload_libraries on all servers and do the CREATE EXTENSION on the primary. Only the primary runs jobs and after the failover the new primary will run them.

**Comment by p0mp0k0** [comment]
Thanks.
