### ISSUE TITLE
pg_cron did not execute the job

### ISSUE THREAD

**Issue by p0mp0k0** [citusdata/pg_cron#86]
I installed the pg_cron in postgresql 11 at centos 7.4, I can see the log 'pg_cron scheduler started', but none of the schedule job can execute, and nothing in log. 
pg_cron_11.x86_64                     1.2.0-1.rhel7                    @pgdg11  
postgresql11.x86_64                   11.4-1PGDG.rhel7                 @pgdg11  
postgresql11-contrib.x86_64           11.4-1PGDG.rhel7                 @pgdg11  
postgresql11-devel.x86_64             11.4-1PGDG.rhel7                 @pgdg11  
postgresql11-libs.x86_64              11.4-1PGDG.rhel7                 @pgdg11  
postgresql11-server.x86_64            11.4-1PGDG.rhel7                 @pgdg11

**Comment by p0mp0k0** [comment]
I found the reason, I start pg server using both ipv4 and ipv6, the pg_cron use ipv6 to connect server, but ipv6 connection refused by pg_hba.conf default ipv6 setting, I changed ipv6 setting in pg_hba.conf, it worked.

**Comment by dekardkrr** [comment]
Could you show what are you changed in pg_hba.conf?
