### ISSUE TITLE
PostgreSQL 12 debs

### ISSUE THREAD

**Issue by airhorns** [citusdata/pg_cron#91]
`pg_cron` builds fine for me against PG 12 with `postgresql-server-dev-12` installed. Any chance we could get debs built and published for official support against PG 12? 

Thanks for an awesome open source library!

**Comment by yingw787** [comment]
Hmm, when I'm building it with `postgresql-server-dev-12` on Ubuntu 19.10 eoan, I get an error when I'm trying to use the package in `psql`:

```text
yingw787=# CREATE EXTENSION pg_cron;
ERROR:  unrecognized configuration parameter "cron.database_name"
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
yingw787=# 
```

**Comment by yingw787** [comment]
oof, I can't read a readme. I should go do that instead :see_no_evil:

**Comment by ppKrauss** [comment]
Any news here, it is a bug? Using UBUNTU 12 and pg12.

-----

```sh
psql postgres://postgres@localhost -c "select version()"
 #   PostgreSQL 12.9 (Ubuntu 12.9-2.pgdg20.04+1) ...
# ... afer sudo apt update; sudo apt upgrade
sudo apt install postgresql-12-cron
  # ... all ok.
sudo service postgresql restart
psql postgres://postgres@localhost -c "CREATE EXTENSION pg_cron"
 # ERROR:  unrecognized configuration parameter "cron.database_name"
 # CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
 
psql postgres://postgres@localhost -c "show hba_file"
  # /etc/postgresql/12/main/pg_hba.conf
grep trust /etc/postgresql/12/main/pg_hba.conf
  # host    all             all             127.0.0.1/32            trust
```
Conclusion: **is a bug**.

**Comment by marcocitus** [comment]
As far as I know PostgreSQL binaries are available via apt.postgresql.org

The CREATE EXTENSION issue is due to the absence of `shared_preload_libraries = 'pg_cron'` in postgresql.conf

**Comment by ppKrauss** [comment]
Was a "README bug", see [issues/175](https://github.com/citusdata/pg_cron/issues/175#issuecomment-1007838394) and [commit/17a069](https://github.com/citusdata/pg_cron/commit/17a069769bebc0d25baa94b51a6df600c385e307). Thanks @marcocitus!
